[project]
name = "sqlalchemy-seedify"
version = "0.1.0"
description = "Idempotent database seeding for SQLAlchemy"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sqlalchemy>=1.4.0",
]
